#!/bin/bash

case $# in
1) BIN="$1" ;;
*) echo "Usage: $0 ExecutableFile" ; exit 1 ;;
esac

if [ ! -f "$BIN" ]
then
	echo "No such executable: $BIN"
	exit 1
fi

if [ ! -x "$BIN" ]
then
	echo "$BIN is not executable"
	exit 1
fi

if [ ! -d tests ]
then
	echo "No tests/ directory here. Are you in the right directory?"
	exit 1
fi

for tt in tests/*.sh
do
	t=`echo $tt | sed -e s/.sh/.exp/g`
  DIFF=$(diff <(./$tt) <(cat ./$t))
  if [ "$DIFF" != "" ]
  then
    echo Failed $tt
  else
    echo Passed $tt
  fi
done
